# Generated by Django 5.0 on 2023-12-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0003_useraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='email',
            field=models.EmailField(default='luke@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='password',
            field=models.CharField(default='password', max_length=50),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(default='Matheny', max_length=50),
        ),
    ]
