# Generated by Django 5.0 on 2023-12-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0004_alter_useraccount_email_alter_useraccount_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_username', models.CharField(default='demo', max_length=50)),
                ('correct_password', models.CharField(default='demo', max_length=50)),
            ],
        ),
    ]
