# Generated by Django 5.0 on 2023-12-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0006_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='person',
            name='bio',
            field=models.TextField(default='Lives in Tampa'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(default='Bon', max_length=255),
        ),
    ]
